name: Tests

on:
  pull_request:
    branches: [ main, testpypi ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Filter Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'
              - 'tests/**'
              - '.github/workflows/**'

      - uses: actions/checkout@v4
        if: steps.changes.outputs.src == 'true'

      - uses: actions/setup-python@v5
        if: steps.changes.outputs.src == 'true'
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        if: steps.changes.outputs.src == 'true'
        uses: astral-sh/setup-uv@v7

      - name: Run Tests
        if: steps.changes.outputs.src == 'true'
        run: |
          uv venv
          source .venv/bin/activate
          uv sync
          uv run pytest -q

      - name: No Tests Required
        if: steps.changes.outputs.src == 'false'
        run: |
          echo "No Tests Required, skipping tests."

