name: Tests

on:
  pull_request:
    branches: [ main, main-testpypi ]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.filter.outputs.src }}
    steps:
      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'
              - 'tests/**'
              - '.github/workflows/**'

  pytest:
    needs: filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11","3.12","3.13","3.14"]
    steps:
      - uses: actions/checkout@v4
        if: needs.filter.outputs.run_tests == 'true'
      - uses: actions/setup-python@v5
        if: needs.filter.outputs.run_tests == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV and Run Tests
        if: needs.filter.outputs.run_tests == 'true' 
        run: | 
            pip install uv
            uv venv
            source .venv/bin/activate
            uv sync
            uv run pytest -q

      - name: No Tests Required
        if: needs.filter.outputs.run_tests == 'false'
        run: |
          echo "No Tests Required, skipping tests."

